- name: Join kubernetes cluster
  shell: kubeadm join --token={{ kubeadm_token }} {{ kubernetes_master_ip }}

- name: Deploy addons pods | grafana and prometheus pods
  shell: kubectl --kubeconfig ./admin.conf apply -f https://raw.githubusercontent.com/giantswarm/kubernetes-prometheus/master/manifests-all.yaml

- name: Deploy addons pods | kubernetes Dashboard pods
  shell: kubectl --kubeconfig ./admin.conf apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
## TO DO Deploy jenkins pods
